### ISSUE TITLE
I cannot install python2-scons in my Manjaro system

### ISSUE THREAD

**Issue by fu123456** [bartoszek/AUR-python2-scons#3]
Hi, I try to install python2-scons package in my Manjaro system by
`yaourt -Sy python2-scons`
But it outputs some errors, and please see the log file (here https://drive.google.com/open?id=1dbLNVklVBF114O3k733fa4T3yYskbd68). Can you help me solve this issue? Thanks.

**Comment by Milad-Rakhsha** [comment]
I am wondering if anyone figured out a solution for this issue?

**Comment by bartoszek** [comment]
@fu123456 @Milad-Rakhsha It looks like #1 to me :thinking:
Please check if updating java to version higher than `9` helps.
Edit: Yep, I'm pretty sure, it's the same issue, closing.
